### ISSUE TITLE
Add RSS|Atom feeds

### ISSUE THREAD

**Issue by hs0ucy** [jr-b/radiocanadalite#1]
Hi,
Thanks for this project, it's more than welcome. 🥳 

But an RSS|Atom feed would be great. 😉 

Thanks, have a nice day!

Ciao ciao 🖖🏻

**Comment by jr-b** [comment]
Salut Hugo!

Content de savoir que le projet te plait! Je viens de voir que tu avais partagé le lien sur ton site perso.

Je regarde ça pour les fils RSS, ça me semble assez simple à mettre en place.

**Comment by hs0ucy** [comment]
Salut @jr-b,

Je l'ai aussi partagé sur Mastodon https://jasette.facil.services/@hs0ucy/110028242505722958. 😉 

Et ç'a généré une petite discussion.

Je suis content que tu sois ouvert à ajouter un flux de syndication ... Si tu as besoin d'un testeur, fais-moi signe.

Ciao 🖖🏻

**Comment by jr-b** [comment]
@hs0ucy Je viens de merge la branche! 

Les fils RSS sont générés par section, par exemple: https://radiocanadamini.ca/rss/politique.xml

**Comment by hs0ucy** [comment]
> @hs0ucy Je viens de merge la branche!
> 
> Les fils RSS sont générés par section, par exemple: https://radiocanadamini.ca/rss/politique.xml

Cool 🥳 

Merci 🙇🏻

**Comment by jr-b** [comment]
Merci pour la suggestion. Hésite pas si tu as des commentaires sur les fils RSS ou sur autre chose!
